### ISSUE TITLE
Zen system

### ISSUE THREAD

**Issue by Mosch0512** [MUnique/OpenMU#116]
As far of what i already know this server does not support zen drops as an item and automatically adds it to your zen. 

But isn't that indirectly destroying the feeling people have with MU Online (for me that would be the case... i can not imagine the sound of Zen without seeing the Zen on the Ground)

I would try to implement an easy working Zen system.

**Comment by sven-n** [comment]
Yes, you're right. It might be nice to have optional zen/money drops.

I think a solution could look like that:
* A new class DroppedMoney (additional to DroppedItem) which implements ILocateable
  * Common stuff could be extracted into a base class
* Extension of GameMap, so it can take and return DroppedMoney
  * GameMap.Add
  * GameMap.GetDrop; maybe add GetMoneyDrop, or change return type to ILocateable
* Adapted pickup logic in PickupItemAction
* a new view plugin interface IShowMoneyDropPlugIn
* Extension of ObserverToWorldViewAdapter, so it considers money drops and calls IShowMoneyDropPlugIn
* a view plugin ShowMoneyDrop which creates and sends the packet to show zen on the ground.
* Adapted IDropGenerator and DefaultDropGenerator, so that it's not adding money to the player but returns a money amount somehow
* Adapted handling of the DropGenerator result in Monster.DropItem
  * Nice to have: Moving this whole drop logic into a new plugin implementation of IAttackableGotKilledPlugIn

**Comment by Mosch0512** [comment]
Cool i will try to follow your ideas if possible. But i will start with #5. Because i want to have an cool launcher :D

**Comment by jhonynet** [comment]
Feature Branch: `zen-system`

**Comment by jhonynet** [comment]
i'm working on this....

**Comment by jhonynet** [comment]
- [ ] New class DroppedMoney (additional to DroppedItem) which implements ILocateable
- [ ] Extension of GameMap, so it can take and return DroppedMoney
- [ ] Adapted pickup logic in PickupItemAction
- [ ] View plugin interface IShowMoneyDropPlugIn
- [ ] View plugin ShowMoneyDrop
- [ ] Extension of ObserverToWorldViewAdapter, so it considers money drops and calls IShowMoneyDropPlugIn
- [ ] Adapted IDropGenerator and DefaultDropGenerator
- [ ] Adapted handling of the DropGenerator result in Monster.DropItem

**Comment by sven-n** [comment]
Fixed with PR #183.
Money drops are now on by default. However, it’s possible to deactivate them in the game configuration on the admin panel. If deactivated, money is added directly to the characters inventory.
