### ISSUE TITLE
[BUG] Magic Effect doesn't remove Icon

### ISSUE THREAD

**Issue by ThisMushroom** [MUnique/OpenMU#166]
As I've figure out whenever magic effect timed out NO packet for magic effect update with "isActive = false" is sending.

It results in that buff is over and no bonus can be observed (e.g. Greater Defence from Elf) but Icon and visual effect of buff is still present.

I've also observed that when it try to get IDeactivateMagicEffectPlugIn from currentlyEffectivePlugIns there is no such plugin.

**Comment by sven-n** [comment]
Thanks for reporting :)

**Comment by sven-n** [comment]
I had a quick look at the issue. Actually, there is an implementation of IDeactivateMagicEffectPlugIn at DeActivateMagicEffectPlugIn.
The problem is, it implements two view plugins and the ```MUnique.OpenMU.PlugIns.CustomPlugInContainerBase<TPlugIn>``` doesn't support this. TPlugIn is IViewPlugIn in this case, and it adds a plugin only with its first implementing interface which inherits from IViewPlugIn:
```csharp
        protected override void ActivatePlugIn(TPlugIn plugIn)
        {
            base.ActivatePlugIn(plugIn);
            var viewInterface = GetInterfaceType(plugIn); // <-- could be more than one view interface, but only handles the first one
            ...
```

So, there are two ways of fixing it:
  * Allowing more than one view interface per Plugin.
  * Separating the DeActivateMagicEffectPlugIn into two classes. And the code should be checked if there are other plugins like this.

I would prefer the first way, as it makes it less error-prone.
