### ISSUE TITLE
doc/packets about LoggedIn

### ISSUE THREAD

**Issue by Tocher** [MUnique/OpenMU#17]
in docs very good write about character select/start/etc, can you add about LoggedIn, which packet type, code/subcode and how to send login/pass to server.
thx

**Comment by sven-n** [comment]
Do you mean the packet structure of the login packet (C3 F1 01)?
Sure, I can add it :)

**Comment by Tocher** [comment]
yeah, i'm trying to write browser client on js, so i start to read about packet structure and now trying to login and about enc/dec ;)
so this information will be very useful!

**Comment by sven-n** [comment]
Nice idea ;)
You may be interested in this: https://github.com/WoLfulus/node-mupacket

**Comment by sven-n** [comment]
Added description with commit https://github.com/MUnique/OpenMU/commit/8f0fdc7dd72b10243c72f1bf68b47d023c5ee9cf

**Comment by Tocher** [comment]
😍

**Comment by WoLfulus** [comment]
there might be some bugs in that repository, and I wrote it around version 0.14 of node if I'm not mistaken. Also, there's a better version of the encdec algorithm here https://github.com/navossoc/SimpleModulus

And if you're writing a browser client, you won't be able to directly connect to the server because you can't use raw tcp sockets. You'll need to write a proxy server that forwards messages from the browser to the game server (and the communication from browser -> proxy can be anything you're comfortable with)

**Comment by Tocher** [comment]
thx

yeah, i think about browser connect to nodejs server via websockets/or else
nodejs like proxy to server with mu protocol.

**Comment by Tocher** [comment]
hi again)
i'm use your enc/dec algorithm and write it on nodejs, then i choose my target some public server and capture some packets.

i receive hello from server ('c1,4,0,1,')
then select server and try to login

i hope this is C3 XX F1 01 ....

`c3,5a,5f,19,7,32,49,cc,76,5b,ec,4e,7b,97,12,2,14,58,b2,93,bc,f5,8e,bb,d3,ea,33,e1,c5,f9,b1,6d,c,b9,8c,1a,9d,19,cd,18,c7,e0,81,39,d9,ec,58,96,57,6e,93,21,c3,a0,6d,6b,5e,ea,b5,59,7a,84,dd,a1,54,bd,9d,a8,62,e8,40,5f,0,b0,e1,26,5d,db,ee,66,82,13,f9,54,18,92,4c,e8,ae,90`

in base64
`w1pfGQcyScx2W+xOe5cSAhRYspO89Y670+oz4cX5sW0MuYwanRnNGMfggTnZ7FiWV26TIcOgbWte6rVZeoTdoVS9nahi6EBfALDhJl3b7maCE/lUGJJM6K6Q`

i tried decrypt with every key i have, but i can't get right decrypted packet.
the closest one was:
`C3-3C-F1-F0-A3-7D-3C-8C-FA-F9-6B-AF-BC-18-C9-78-E9-C1-00-C4-3C-30-2A-F1-E4-76-54-78-1F-DD-52-09-03-73-96-D5-4B-DD-C5-28-64-10-A3-0B-26-B4-2A-EA-4B-36-EF-49-F4-C7-EC-75-67-EE-CA-B7`

maybe you know what i'm doing wrong? :(

**Comment by Tocher** [comment]
aso i'v check enc1.dat and dec2.dat in client data folder, and it's the same with DefaultKeys in repo.

**Comment by sven-n** [comment]
Hi!
You also need to make sure your Xor32 key is the correct one. I posted a short guide about how to retrieve it by using simple chat packets at [here](http://forum.ragezone.com/f508/munique-openmu-source-server-project-1141294-post8838707/#post8838707).
Packets which are sent to the server are first encrypted by Xor32, then by SimpleModulus. So you need to decrypt first by SimpleModulus, then by Xor32 - that's also what the [Decryptor](https://github.com/MUnique/OpenMU/blob/5706e4474ff0aee5abe44b180b81a58db2ba9895/src/Network/Decryptor.cs) class does.
The login packet is also a special case, because login name and password are additionally "encrypted" by Xor3, so you may have a look [here](https://github.com/MUnique/OpenMU/blob/d8d82f5c430cb9ac75df77e996d354457b18ecd5/src/GameServer/MessageHandler/LoginHandler.cs#L67) ;)

I hope this helps you :)

**Comment by Tocher** [comment]
thx a lot!
i'm login to the server and send message, so i have Xor32 key, is it correct xor32? :)
i need just put key [here](https://github.com/MUnique/OpenMU/blob/master/src/Network/Xor/DefaultKeys.cs#L26)?
or some else moves? ;)
```
var decrypted = ParseByteString("c1 11 00 6e 3c a3 f3 48 d2 c1 97 3b 4a a8 bb f4 e7");
var encrypted = ParseByteString("c1 11 00 61 61 61 61 00 00 00 00 00 00 61 73 64 00");

Result: 00 00 00 0F 3C A3 F3 29 D2 C1 97 3B 4A C9 A9 E3 83 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by sven-n** [comment]
yes, either replace the default key or pass your key in the constructor of the Decryptor.
However, the key you calculated is not complete. You need to send a bigger chat message with at least 22 characters. Longer is always better, because the code would verify if it's correct :)

**Comment by Tocher** [comment]
yeaa!
22-24 characters works well, but at first i mix up enc and dec key ;)
and i notice if send a big message (30-35 characters) i have 2 packets to server, and 1 from. 😕 
```
c1,5,18,13,ab
c1,5,18,13,ab,c1,34,0,6e,3c,a3,f3,48,d2,c1,97,3b,4a,f8,aa,b2,95,e7,6e,71,a0,99,d6,eb,b9,fa,e8,7b,9b,f2,58,c2,ff,3d,28,7c,12,8d,cf,10,ec,98,a6,60,7a,95,ce,c2,8d,b0,77,5f

c1,34,0,61,61,61,61,0,0,0,0,0,0,31,32,33,34,35,36,37,38,39,30,2d,3d,71,77,65,72,74,79,75,69,6f,70,5b,5d,61,73,64,66,67,68,6a,6b,6c,3b,27,5c,7a,78,0
```
thank you very much!
