### ISSUE TITLE
AdminPanel doesn't render relevant ItemDescription Drop-down items

### ISSUE THREAD

**Issue by tabilzad** [MUnique/OpenMU#186]
**Describe the bug**
Seems like most/all of the `ItemDescription` drop downs only list the names of the Orbs when trying to add an item to merchants store or characters inventory etc.
**To Reproduce**
1. Go to Game Configuration
2. Under JewelMixes click on `Create`
3. Both of the dropdowns here only list the names of the skill Orbs

**Expected behavior**
A larger list of description specific items, categories of items. Jewel names under Jewel dropdows etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/16094286/80759534-13b1cd80-8afd-11ea-8e53-82dff24a51ab.png)

**Comment by sven-n** [comment]
It’s not a bug, but this [control](https://github.com/Blazored/Typeahead) is more like a search control. You’d need to enter the name (or a part of it) of the item, then it displays the corresponding items in the list.

I’m thinking of removing the drop down button, because it’s misleading in our use case.

**Comment by tabilzad** [comment]
oh i see, closing then
