### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [MUnique/OpenMU#311]
I'd like to help, how can I help?

**Comment by Mosch0512** [comment]
https://github.com/MUnique/OpenMU/projects/7

If you know C# build the project get it running and than work on one of the chat commands :)

**Comment by Leonardo-Ferreira** [comment]
quick question, is there a live version where I could play with other players?

**Comment by sven-n** [comment]
> quick question, is there a live version where I could play with other players?
Hi! There is a test server of a community member: http://www.bloodmu.org/
Please don't expect that your accounts will live there forever - it's a test server - and some updates still need a fresh database.

> I'd like to help, how can I help?
Nice! :) If you want to contribute code, chat commands are an easy way to get started. The other stuff probably needs some deeper knowledge.
However, every help is welcome - testing the server and giving hints for improvements help us to make it better, too.

**Comment by Leonardo-Ferreira** [comment]
ok cool!

Particularly speaking, im quite experienced on performance and scalability... any chance you got standing issues on those topics?

**Comment by sven-n** [comment]
Nice!
Well, currently we don't have that many performance issues.
Recently, I got a report, that the gameplay gets laggy after some hours of gaming on a spot on that test server. After re-login the problem was gone. I didn't look at that problem yet, but you could ask Rafal at our discord about it.

Other than that, this project can be deployed in a distributed way, where the single services communicate over Dapr. I didn't optimize that yet. You can see the open points at the [Dapr project board](https://github.com/MUnique/OpenMU/projects/8).
