### ISSUE TITLE
I want to implement such an effect about wearing a set of +10 or higher equipments.

### ISSUE THREAD

**Issue by terry83299387** [MUnique/OpenMU#344]
I want to implement such an effect that when the character wears a set of +10 or higher equipments, they can get an additional 5%~30% of defense, just like the official does.

But I haven't found a good way to write the code at the moment, the current Attribute System doesn't seem to support this feature easily, do you have any good suggestion?

Thank you.

**Comment by sven-n** [comment]
I thought that it would work already - I'll check it soon.
AFAIK, it should work by defining item set groups.

**Comment by terry83299387** [comment]
It doesn't seem appropriate to use Item Set Group to do this. At least three reasons:
1. Each set of equipments has to define a Set Group Definition individually (as each Set Group Definition needs associate a set of items), which leads to a lot of work and data redundancy.
2. Mixing cases that cannot be handled well, such as one +10 helm and four +11 other parts, should be treated as a +10 set. This logic is not well defined by Item Set Group.
3. For the same set of equipments, such as Plate, the Magic Gladiator does not need a helm, while the Dark Knight needs all 5 parts to function.

**Comment by terry83299387** [comment]
I've done this in a hardcoded way —— which is the only way I can think of at the moment.
I'm not very satisfied, although it works well during testing.

**Comment by sven-n** [comment]
> Each set of equipments has to define a Set Group Definition individually (as each Set Group Definition needs associate a set of items), which leads to a lot of work and data redundancy.

I found this code here: https://github.com/MUnique/OpenMU/blob/01572855ccb731540b13365a9ce8efdab2354243/src/Persistence/Initialization/Items/ArmorInitializerBase.cs#L53

I think the issue here is, that the created objects are not appended to the GameConfiguration, and therefore not loaded and not effective.
However, I agree, that it's a lot of redundant data at first sight - need to test if that has some negative impact.

> Mixing cases that cannot be handled well, such as one +10 helm and four +11 other parts, should be treated as a +10 set. This logic is not well defined by Item Set Group.

I think mixing these items is not a problem. It's handled in the ItemPowerUpFactory.GetSetPowerUps.
There are also some unit tests for that.

> For the same set of equipments, such as Plate, the Magic Gladiator does not need a helm, while the Dark Knight needs all 5 parts to function.

Yes, that's correct. When equipping a Plate set, a Magic Gadiator cannot get the defense bonus - that's also the case in the original server. However, MG sets don't include a helm and will be seen as complete even without wearing a helm.

**Comment by terry83299387** [comment]
Very helpful. Thank you so much. :)
I'll try it next.

**Comment by sven-n** [comment]
I fixed it, thanks for reporting :)
