### ISSUE TITLE
Use Span<T> (and Pipe API) for network code and packet handling

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#35]
C# offers a new way to handle pieces of arrays: [C# - All About Span: Exploring a New .NET Mainstay](https://msdn.microsoft.com/en-us/magazine/mt814808.aspx). I think it could help to improve the performance in the network code and would result in a lower amount of heap allocations in this project. This means, the garbage collector would have less work to do.

Currently, we make good use of byte arrays, e.g. for every received network packet at least one byte array is created. If a packet was encrypted, e.g. by SimpleModulus, even more byte arrays are created.

**Comment by sven-n** [comment]
I tested it a bit and created a branch for it: https://github.com/MUnique/OpenMU/tree/span

**Comment by sven-n** [comment]
The new Pipe API could be amazing for this projection, too :)

More info about the new API can be found here: https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html

**Comment by sven-n** [comment]
The new Pipe API could be amazing for this project, too :)

More info about the new API can be found here: https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html

**Comment by sebastian-heinz** [comment]
I would have the following suggestions to improve the network performance:
1. To avoid GC to collect objects, all objects should be initialised on startup and reused. So that no `new`-keywords are necessary during the network read / write operations and references are kept.
2. A big buffer array (to pin it on the large object heap [https://stackoverflow.com/questions/8951836/why-large-object-heap-and-why-do-we-care]) should be created and potions of it should be assigned to the `SocketAsyncEventArgs` via `SetBuffer()`-Method. This prevents compacting of the buffer thus improves performance.
3. To avoid copying memory / object instantiation we should use Span<T>
4. This will be only possible by limiting the total number of connections from the beginning. As the necessary resources would be calculated on startup. (Ex. BufferSize = MaxConnections * BufferSize, Number of instantiated `SocketAsyncEventArgs`at the beginning, etc. will all be based on that number)
5. Additionally investigate if the c# Pipeline is better than a big buffer. (https://github.com/dotnet/corefx/issues/31953) As there might be some concerns with implementation.

The following changes should be applied to https://github.com/MUnique/OpenMU/blob/master/src/Network/Listener.cs and https://github.com/MUnique/OpenMU/blob/master/src/Network/Connection.cs as they look like the Server / Client core parts of the application if I'm not mistaken.

I would propose the following process of change:
1. Start by creating an Interface for `Listener` and `Connection` classes, so the implementation can be swapped.
2. Create a test to measure the performance. (By load testing and measuring times, as well as external monitoring of CPU and Memory)
3. Try to create an Implementation with the above suggested changes.
4. Compare results and draw conclusions where we can improve further.

This would not yet introduce Span<T> to the whole project, but on a smaller level that we then might be able to test with some test cases sending and modifying alot of data (what the server usually would do) After a successful result we can discuss on exposing/returning the Span<T> parts or other steps that can help to read/write the data more easy / performant.

If any of these steps are not reasonable or another workflow should be taken, I'm happy to discuss on that so we can find a way to improve the performance together.

**Comment by sven-n** [comment]
Well, I would propose to make it as simple as possible in a first step. For the sake of simplicity we should not case about managing our own memory ;-)

That means:
  * Using System.Buffers.MemoryPool in the PlayerView implementation instead of the currently used byte arrays. One thing to note: C3/C4 packets require slightly more space when they are encrypted. So it might be needed to use a memory pool during the encryption (SimpleModulus) too.
  * System.IO.Pipelines and Span<byte> in the Connection class and encryption stuff. Luckily for us, we can expect that decrypted packets are not bigger than the encrypted ones.

I have already started doing some transformation of the Connection class to use PipeReader and PipeWriter (interesting article: https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/). However, I'll need to update the span-branch to the state of the current master branch first. I did a migration to .net standard/core on master which is not in span yet. After that, I'll try to integrate my changes of the Connection class. I'm quite busy at the moment, so this could take some days.

When that works, we could write some benchmark tests and see how much changed in terms of speed and heap allocations. If required, we can then optimize further.

**Comment by sven-n** [comment]
To make use of pipelines with sockets there is this project (with nuget package): https://github.com/mgravell/Pipelines.Sockets.Unofficial

**Comment by sven-n** [comment]
Added a branch/PR with my current state.

**Comment by sven-n** [comment]
I added a benchmark, and I have to say... I'm utterly impressed. I'm searching for errors in my methodology, but I can't find them. If you can, please tell me ;-)

You can find the code of the benchmark [here](https://github.com/MUnique/OpenMU/blob/401b4d3c0b060a18e18ae745b2d36a1a1911cacd/tests/MUnique.OpenMU.Network.Benchmarks/EncryptionBenchmarks.cs).

The results:
``` ini

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17134.345 (1803/April2018Update/Redstone4)
Intel Core i5-3570 CPU 3.40GHz (Ivy Bridge), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=2.1.400
  [Host]     : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
  Job-VXAUGJ : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT

Runtime=Core  InvocationCount=10  UnrollFactor=1  

```
|                          Method |           Mean |         Error |        StdDev |      Gen 0 |   Allocated |
|-------------------------------- |---------------:|--------------:|--------------:|-----------:|------------:|
| PipelinedSimpleModulusEncryptor |       3.493 us |     0.2589 us |     0.7132 us |          - |     4.85 KB |
|          SimpleModulusEncryptor | 687,805.169 us | 6,397.1918 us | 5,670.9434 us | 15500.0000 | 47656.55 KB |


If I read (and calculate) this correctly, the pipelined version is almost 200000 times faster while allocating no additional memory during encryption. If it would allocate just a one byte per packet, we would see over 100 KB allocated ;-)

**Comment by sven-n** [comment]
Merged pipe branch into master :)
