### ISSUE TITLE
Porting to modern C++?

### ISSUE THREAD

**Issue by tehKaiN** [MUnique/OpenMU#36]
I'm thinking about setting up a tiny playground server on my orangepi and I'm curious if you'd be interested in porting your sources to modern C++ since it's more portable, features safe mem allocation and most of other stuff which make people use C#. I'd of course help with such process. If not, is there any reason I'm not seeing to use C# beside just a matter of preference?

Another added bonus is independence from Visual Studio - one could just use clang/gcc and build it with single make command without bloating HDD with another IDE.

I was with muo since 2k5 until about 2012 doing minor dev and I have periodically some thoughts about returning to this game. I'm glad that there are some open movements in development these days - you're doing amazing work!

**Comment by sven-n** [comment]
Hi, at the moment I don't have the time and motivation to port it to any other language. It's in C# because I'm most productive by using it than with any other language for this task. It also has a rich ecosystem with a lot of available frameworks and tools.
You can also compile it under linux without having a VS installed, except for some JSX files. TravisCI for example actually runs under linux. I'm currently working at porting the web stuff to Redux and TypeScript, then it should compile completely under Linux, too. After that, I'm thinking about porting it to .net core to make it even more portable :)
I also had the idea about automatic pulling of new releases and directly deploying it on a small server for testing ;)

**Comment by sven-n** [comment]
I don't think I'll ever have that much time, so no ;)
