### ISSUE TITLE
Can I help with any tasks?

### ISSUE THREAD

**Issue by khaiodev** [MUnique/OpenMU#388]
Firstly, the project is really cool, congratulations on the initiative, despite it being a few years old.

I would like to know how I can help the community :)

**Comment by sven-n** [comment]
Do you have knowledge about kubernetes? We could need a configuration of the [distributed deployment](https://github.com/MUnique/OpenMU/tree/master/deploy/distributed), but instead of docker-compose, it'd be nice to support kubernetes somehow.
Apart of that, you could check if any open issue or anything on the [projects](https://github.com/MUnique/OpenMU/projects?type=classic) interests you :)

**Comment by khaiodev** [comment]
Cool. I do know K8s and we can work to create a deploy for the environments and work staging.

I'll take a look at the board and sign something to contribute.

**Comment by sven-n** [comment]
Nice, thank you. Let me know if you have any questions.
