### ISSUE TITLE
Attribute Requirements for GameMaps

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#50]
Some maps have "special" requirements, which a Character has to fulfill until it can enter or even stay at it.

### Icarus
Requires that a Character wears a Wing, Cape or a Dinorant.
Idea:
  * Add a attribute "CanFly" with a value of 1 to all wings, capes and dinorant at their ItemDefinition.BasePowerUpAttributes.
  * Add a requirement to Icarus, where "CanFly" needs to be at least 1.

### Kanuru Event Map
Requires that a Character wears a "Moonstone Pendant".
Idea:
  * Add a attribute "MoonstonePendantEquipped" with a value of 1 to the ItemDefinition.BasePowerUpAttributes of the Moonstone Pendant.
  * Add a requirement to the event map, where "MoonstonePendantEquipped" needs to be at least 1.
  
## Required extensions
  * GameMapDefinition needs a collection of AttributeRequirements
  * The GameLogic needs to be extended so that the requirements are checked before entering the map and when equipped items are changed

## What else can we do with that?
Well, this leaves much room for customization. There could be "VIP" maps, which could require certain attributes. Not just for paying customers, but possibly also game masters. Another idea could be event maps which require that players equip a certain item, e.g. a race track map which require to wear a Unicorn.

**Comment by nmarazov** [comment]
Hi, Great work on the project.
I want to contribute and started working on this feature but I encounter some problems.
I already have a somewhat working version of map requirements. Right now i implemented a Many-to-Many relation between AttributeRequirement and GameMapDefinition (with separate table mapping between the two) but when i try to add something it crashes because of access permissions. I added permissions manually and it works but i don`t know how to add them to the DB migration. I can create a pull request for you to see what i have done.

**Comment by sven-n** [comment]
Hey, thank you :)
Sure, just create a branch and commit the changes, so I can take a look. No pull request required yet ;)

**Comment by sven-n** [comment]
Will be solved with #122.
