### ISSUE TITLE
[Features] JSON configurations

### ISSUE THREAD

**Issue by afrokick** [MUnique/OpenMU#58]
As a client side, I want to have JSON file with all configurations for items, characters and etc.

It would be perfect to use server side DataModel's project in client side application.

**Comment by sven-n** [comment]
I’m working on it... my plan is:
  * Building an extended data model (like the one of Persistence.EntityFramework, but simpler), which can be (de)serialized by Newtonsoft.Json without much hassle.
  * Building a reuseable project (nuget package) which can be used by external programs, e.g. a client.
  * Using this new data model in Persistence.InMemory, since it should be independent of the EntityFramework model.
  * Just an idea: Later we could re-use the same data model and (de)serialization code when implementing a Persistence project for NoSql databases, e.g. RavenDB.

**Comment by sven-n** [comment]
Almost there... Can already export a GameConfiguration of my basic DataModel implementation as json.

Currently searching a way to convert objects between different kind of DataModel implementations. I had a look at AutoMapper, but didn’t get it to work correctly yet.
Why do I need this? Because I want to be able to save all implementations of the DataModel under the same basic json format :)

**Comment by sven-n** [comment]
Status update: Almost done. Instead of AutoMapper I’ll use Mapster which works great, except of a minor issue - I already sent a pull request for a fix.

**Comment by sven-n** [comment]
Committed the current state with:
https://github.com/MUnique/OpenMU/commit/6a97fa9e334b793acb60b825b06564d339a674b4
https://github.com/MUnique/OpenMU/commit/11a3e509da596c1d6cce2de9a367c9cfe3141484

Now, I'm waiting until my pull request of Mapster will be accepted. When it's done, we can download the game configuration by using a link to the admin panel: http://localhost:1234/data/gameconfiguration.json

This file will be can be read in again with the Persistence.BasicModel.GameConfiguration.FromJson(...) method.

**Comment by sven-n** [comment]
Mapster has been updated, the download of the gameconfiguration.json works now :-)

@afrokick How do you plan to make use of it in your client project? Do you need a nuget package?

**Comment by afrokick** [comment]
Don't know.. may be dll or source file.
